// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBackupJob(arg1) {
  return window['go']['main']['App']['AddBackupJob'](arg1);
}

export function AddDatabase(arg1) {
  return window['go']['main']['App']['AddDatabase'](arg1);
}

export function AddStorageTarget(arg1) {
  return window['go']['main']['App']['AddStorageTarget'](arg1);
}

export function DeleteBackupJob(arg1) {
  return window['go']['main']['App']['DeleteBackupJob'](arg1);
}

export function DeleteDatabase(arg1) {
  return window['go']['main']['App']['DeleteDatabase'](arg1);
}

export function DeleteStorageTarget(arg1) {
  return window['go']['main']['App']['DeleteStorageTarget'](arg1);
}

export function GetBackupHistory(arg1) {
  return window['go']['main']['App']['GetBackupHistory'](arg1);
}

export function GetBackupJob(arg1) {
  return window['go']['main']['App']['GetBackupJob'](arg1);
}

export function GetBackupJobs() {
  return window['go']['main']['App']['GetBackupJobs']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDatabase(arg1) {
  return window['go']['main']['App']['GetDatabase'](arg1);
}

export function GetDatabases() {
  return window['go']['main']['App']['GetDatabases']();
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStorageTarget(arg1) {
  return window['go']['main']['App']['GetStorageTarget'](arg1);
}

export function GetStorageTargets() {
  return window['go']['main']['App']['GetStorageTargets']();
}

export function GetTranslations(arg1) {
  return window['go']['main']['App']['GetTranslations'](arg1);
}

export function ParseStorageConfig(arg1, arg2) {
  return window['go']['main']['App']['ParseStorageConfig'](arg1, arg2);
}

export function RunBackupNow(arg1) {
  return window['go']['main']['App']['RunBackupNow'](arg1);
}

export function SaveServerConfig(arg1) {
  return window['go']['main']['App']['SaveServerConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendTestTelegramMessage(arg1, arg2) {
  return window['go']['main']['App']['SendTestTelegramMessage'](arg1, arg2);
}

export function SetAppLanguage(arg1) {
  return window['go']['main']['App']['SetAppLanguage'](arg1);
}

export function SetEventEmitter(arg1) {
  return window['go']['main']['App']['SetEventEmitter'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function TestDatabaseConnection(arg1) {
  return window['go']['main']['App']['TestDatabaseConnection'](arg1);
}

export function TestStorageConnection(arg1) {
  return window['go']['main']['App']['TestStorageConnection'](arg1);
}

export function TestTelegramConnection(arg1) {
  return window['go']['main']['App']['TestTelegramConnection'](arg1);
}

export function ToggleBackupJobActive(arg1, arg2) {
  return window['go']['main']['App']['ToggleBackupJobActive'](arg1, arg2);
}

export function UpdateBackupJob(arg1) {
  return window['go']['main']['App']['UpdateBackupJob'](arg1);
}

export function UpdateDatabase(arg1) {
  return window['go']['main']['App']['UpdateDatabase'](arg1);
}

export function UpdateStorageTarget(arg1) {
  return window['go']['main']['App']['UpdateStorageTarget'](arg1);
}

export function ValidateFolder(arg1) {
  return window['go']['main']['App']['ValidateFolder'](arg1);
}
