// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {config} from '../models';

export function AddBackupJob(arg1:database.BackupJob):Promise<void>;

export function AddDatabase(arg1:database.DatabaseConnection):Promise<void>;

export function AddStorageTarget(arg1:database.StorageTarget):Promise<number>;

export function DeleteBackupJob(arg1:number):Promise<void>;

export function DeleteDatabase(arg1:number):Promise<void>;

export function DeleteStorageTarget(arg1:number):Promise<void>;

export function GetBackupHistory(arg1:database.HistoryFilter):Promise<Array<database.BackupHistory>>;

export function GetBackupJob(arg1:number):Promise<database.BackupJob>;

export function GetBackupJobs():Promise<Array<database.BackupJob>>;

export function GetDashboardStats():Promise<database.DashboardStats>;

export function GetDatabase(arg1:number):Promise<database.DatabaseConnection>;

export function GetDatabases():Promise<Array<database.DatabaseConnection>>;

export function GetServerConfig():Promise<config.ServerConfig>;

export function GetSettings():Promise<database.AppSettings>;

export function GetStorageTarget(arg1:number):Promise<database.StorageTarget>;

export function GetStorageTargets():Promise<Array<database.StorageTarget>>;

export function GetTranslations(arg1:string):Promise<Record<string, any>>;

export function ParseStorageConfig(arg1:string,arg2:string):Promise<any>;

export function RunBackupNow(arg1:number):Promise<void>;

export function SaveServerConfig(arg1:config.ServerConfig):Promise<void>;

export function SaveSettings(arg1:database.AppSettings):Promise<void>;

export function SelectFile(arg1:string,arg2:Array<string>):Promise<string>;

export function SelectFolder():Promise<string>;

export function SendTestTelegramMessage(arg1:string,arg2:string):Promise<void>;

export function SetAppLanguage(arg1:string):Promise<void>;

export function SetEventEmitter(arg1:any):Promise<void>;

export function Shutdown():Promise<void>;

export function TestDatabaseConnection(arg1:database.DatabaseConnection):Promise<void>;

export function TestStorageConnection(arg1:database.StorageTarget):Promise<void>;

export function TestTelegramConnection(arg1:string):Promise<void>;

export function ToggleBackupJobActive(arg1:number,arg2:boolean):Promise<void>;

export function UpdateBackupJob(arg1:database.BackupJob):Promise<void>;

export function UpdateDatabase(arg1:database.DatabaseConnection):Promise<void>;

export function UpdateStorageTarget(arg1:database.StorageTarget):Promise<void>;

export function ValidateFolder(arg1:string):Promise<void>;
